### ISSUE TITLE
Feature - Request/Response Handler(s)

### ISSUE THREAD

**Issue by crobinson42** [js-data/js-data-express#13]
_I was putting in a PR and noticed the requirements. So, I thought I'd open this issue first for discussion._ 

This feature would allow simple extensibility to the module in order for a user to hijack/takeover the response from `js-data-express`. This is useful in a number of circumstances, ie: deleting fields you don't want being sent in the response like `password`.

Setup your resource

```
const UserMapper = store.defineMapper('user')
```

Assign a single response handler method to intercept all responses

```
UserMapper.resHandler = (storeResults,req,res,next) => {
  res.send(storeResults.map(r=>{return r._id}))
  res.end();
};
```

-or-

Assign a response handler per method

```
UserMapper.resHandlers = {
  get: (storeResults, req,res,next) => {
    res.send('get')
  },
  post: (storeResults, req,res,next) => {
    res.send('post')

  },
  put: (storeResults, req,res,next) => {
    res.send('put')

  },
  delete: (storeResults, req,res,next) => {
    res.send('delete')

  },
};
```

Finally, you use this modules `mount()` method to do the work.

```
// Mount queryParser and store at "/api"
mount(app, store, '/api')
```

**Comment by jmdobry** [comment]
I see the end goal you're going for, but I don't think putting "controller" code onto Mappers (Model layer) is the best way to approach it. How about being able to configure js-data-express to act as middleware that subsequently calls your response handlers, without js-data-express itself responding to the request. Example:

``` js
// Mount queryParser at "/"
app.use(queryParser)
// Mount store at "/"
app.use(new Router(store, {
  passThru: true
}).router)

// manually respond on a specific route
app.get('/users/:id', (req, res) => {
  // don't send user's passwordHash to the browser
  res.send(utils.omit(req.jsDataResult, 'passwordHash'));
});

// The routes mounted by js-data-express don't
// respond to the request, instead they attach the
// result to "req", so we respond to the request
// manually here:
app.use((req, res) => {
  if (/* some condition */) {
    // do something custom
  } else if (req.jsDataResult) {
    // Just send the jsData result to the browser
    res.send(req.jsDataResult);
  } else {
    // default response
  }
});
```

Thoughts?

**Comment by crobinson42** [comment]
Hmm. I like your idea but it seems like it would require repetitive boilerplate code. Opt-in to have `js-data-express` "pass-thru" would affect all models/resources in the store, in your example? Someone may only want to assign response handler methods to specific REST endpoint calls and let `js-data-express` handle the rest.

If we could avoid attaching to the mapper (Model layer) but still pass in custom response handlers via store w/ `mount()`, It seems... smooth. ie: https://github.com/js-data/js-data-express/pull/14

**Comment by jmdobry** [comment]
My question is, is it okay for say, the provided `get` resHandler to be used by `two` different js-data-express endpoints? In fact, all of them would be used in more than one endpoint, meaning the user would have to have an `if` statement in their handlers.

What about also allowing the user to provide a resHandler for a specific CRUD method, like `find`, `findAll`, etc.?

**Comment by backlit-studio** [comment]
I like the idea of being able to provide a handler for a specific mapper and endpoint. I think in most cases where I've wanted to do something like this it was not across all models. So if I'm understanding @jmdobry 's proposal, that if/else block might be prone to some clutter. 

What about rather than attaching the handlers to the mapper, you could pass in an object containing the custom handlers as a second argument to the `Router` constructor

Something like:

``` javascript
const userHandlers = {
  get: (result, req,res,next) => {
    delete result.password;
    res.send(result);
  }
}
api.use('/user', new Router(UserMapper, userHandlers).router)
```

And then makeHandler might look something like this: 

``` javascript
function makeHandler (handler, responseHandler) {
  return function (req, res, next) {
    return utils.resolve()
      .then(function () {
        return handler(req)
      })
      .then(function (result) {
        res.status(200)
        if(responseHandler) {
          responseHandler(result, req, res)
        } else {
          if (!utils.isUndefined(result)) {
            res.send(result)
          }
        }
        res.end()
      })
      .catch(next)
  }
}
```

More or less the same as #14 just without attaching the handlers directly to the mapper. Just a rough idea.

**Comment by jmdobry** [comment]
What I'm saying is, if `get` is the key, then that handler would have to handle both `/users` and `/users/:id`, necessitating an `if` statement in the handler. I'm suggesting CRUD-method targeted configuration:

``` js
const userHandlers = {
  // GET /users
  findAll: (results, req,res,next) => {
    results.forEach((result) => {
      delete result.passwordHash;
    })
    res.send(results);
  },
  // GET /users/:id
  find: (result, req,res,next) => {
    delete result.passwordHash;
    res.send(result);
  }
}
api.use('/user', new Router(UserMapper, userHandlers).router)
```

Or even:

``` js
const config = {
  // PATCH /users/:id
  update: {
    method: 'PATCH', // Default is PUT
    request: (req, res, next) => {
      // do something before store.update() gets called

      if (req.body.password) {
        // User is updating their password
        req.body.passwordHash = computeHash(req.body.password)
        delete req.body.passord
      }

      next();
    },
    response: (result, req, res, next) => {
      delete result.passwordHash;
      // Send updated user record to the browser
      res.send(result);
    }
  }
}
api.use('/user', new Router(UserMapper, config).router)
```

**Comment by crobinson42** [comment]
I think @ramirezd42 has a good point, let's make the response handler a second argument. @jmdobry has a great point re `get` being 2 difference endpoints. I like the recommendation of applying `findAll` and `find` handlers.

I'll work on the PR and update shortly

**Comment by backlit-studio** [comment]
This looks good to me. Any thoughts @jmdobry ? My only request would be to add some tests to the Router spec to reflect the new functionality

**Comment by jmdobry** [comment]
This topic raised some usability issues. I like the direction that @crobinson42's PR has taken. I'm going to open another PR (rebased off of #14) that takes things a step further.
