### ISSUE TITLE
package.json main should point at the pre-built version of the script

### ISSUE THREAD

**Issue by backlit-studio** [js-data/js-data-express#4]
The **dist** folder should be tracked and the _"main"_ script in **package.json** should point to **dist/js-data-express.js**. 

I noticed this was how [js-data/js-data](https://github.com/js-data/js-data) was set up. Was there a reason for not doing the same with this repo?

Thanks!

**Comment by jmdobry** [comment]
Fixed in [bc69458](https://github.com/js-data/js-data-express/commit/bc69458ee45adf7247ca39ed6a11a1f065776e7b)
